Repository mju-likelion/12th-hackathon-team1-server, pull requests merged in 2024-07, with the labels that each got.

#5 Feature/#4 .gitmessage.txt 파일 추가
  .gitignore
  .gitmessage.txt
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/hackathonteam1/refreshrator/RefreshratorApplication.java
  src/test/java/com/hackathonteam1/refreshrator/RefreshratorApplicationTests.java
Labels: feature

#2 setting/#1 스프링 부트 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/hackathonteam1/refreshrator/RefreshratorApplication.java
  src/test/java/com/hackathonteam1/refreshrator/RefreshratorApplicationTests.java
Labels: good first issue

#8 Feature/#7 예외 처리를 위한 Exception 및 ResponseDTO 작성
  build.gradle
  src/main/java/com/hackathonteam1/refreshrator/dto/ErrorResponseDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/ResponseDto.java
  src/main/java/com/hackathonteam1/refreshrator/exception/ConflictException.java
  src/main/java/com/hackathonteam1/refreshrator/exception/CustomException.java
  src/main/java/com/hackathonteam1/refreshrator/exception/DtoValidationException.java
  src/main/java/com/hackathonteam1/refreshrator/exception/ForbiddenException.java
  src/main/java/com/hackathonteam1/refreshrator/exception/NotFoundException.java
  src/main/java/com/hackathonteam1/refreshrator/exception/UnauthorizedException.java
  src/main/java/com/hackathonteam1/refreshrator/exception/advice/ExceptionController.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
Labels: feature

#12 Feature/#10 회원가입 기능
  src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/SigninDto.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/repository/UserRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
Labels: feature

#17 Feature/#16 회원가입시 냉장고 생성 기능 추가
  src/main/java/com/hackathonteam1/refreshrator/repository/FridgeRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
Labels: feature

#19 Feature/#9 recipe 등록 API
  src/main/java/com/hackathonteam1/refreshrator/config/AuthenticationConfig.java
  src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/auth/LoginDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/auth/SigninDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/RegisterRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/auth/TokenResponseDto.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/repository/IngredientRecipeRepository.java
  src/main/java/com/hackathonteam1/refreshrator/repository/IngredientRepository.java
  src/main/java/com/hackathonteam1/refreshrator/repository/RecipeRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: feature

#21 Feature/#20 레시피 상세 조회 API
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/RegisterRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/ingredient/IngredientDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/DetailRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/repository/IngredientRecipeRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: feature

#23 Feature/#18 냉장고에 재료추가 API
  src/main/java/com/hackathonteam1/refreshrator/controller/FridgeController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/fridge/AddFridgeDto.java
  src/main/java/com/hackathonteam1/refreshrator/entity/FridgeItem.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/repository/FridgeItemRepository.java
  src/main/java/com/hackathonteam1/refreshrator/repository/FridgeRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
Labels: feature

#25 Feature/24 예외처리 누락 부분 추가 및 수정
  src/main/java/com/hackathonteam1/refreshrator/exception/advice/ExceptionController.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
Labels: enhancement, refactor

#31 Feature/#29 냉장고에 있는 재료 수정 API
  src/main/java/com/hackathonteam1/refreshrator/controller/FridgeController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/fridge/AddFridgeDto.java
  src/main/java/com/hackathonteam1/refreshrator/entity/User.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
Labels: feature

#30 Feature/#27 레시피 재료 추가 API
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/IngredientRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/RecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/exception/BadRequestException.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: feature

#35 Feature/#34 로그아웃 API
  src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java
Labels: feature

#38 Feature/#37 레시피 상세 조회 수정
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/DetailRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/IngredientRecipeResponseDto.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: enhancement

#36 Feature/#28 레시피 재료 삭제 API
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/DeleteIngredientRecipesDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/ModifyRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/RegisterIngredientRecipesDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/RegisterRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: feature

#42 Feature/#13 레시피 삭제 API
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: feature

#44 Feature/#43 엔티티 수정
  src/main/java/com/hackathonteam1/refreshrator/entity/Recipe.java
  src/main/java/com/hackathonteam1/refreshrator/entity/RecipeLike.java
Labels: bug

#57 Feature/#51 회원탈퇴 API
  src/main/java/com/hackathonteam1/refreshrator/config/AuthenticationConfig.java
  src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java
  src/main/java/com/hackathonteam1/refreshrator/entity/Fridge.java
  src/main/java/com/hackathonteam1/refreshrator/entity/User.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
Labels: feature

#50 Feature/#49 냉장고에 있는 재료 단건조회 API
  src/main/java/com/hackathonteam1/refreshrator/controller/FridgeController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/fridgeItem/FridgeItemResponseData.java
  src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
Labels: feature

#58 Feature/ #55 레시피 목록 조회 API
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/PaginationDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/RecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/RecipeListDto.java
  src/main/java/com/hackathonteam1/refreshrator/entity/Image.java
  src/main/java/com/hackathonteam1/refreshrator/entity/Recipe.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/repository/RecipeRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: feature

#65 Feature/ #61 이미지 생성 API
  build.gradle
  src/main/java/com/hackathonteam1/refreshrator/config/S3Config.java
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/file/ImageDto.java
  src/main/java/com/hackathonteam1/refreshrator/exception/FileStorageException.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/repository/ImageRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
  src/main/java/com/hackathonteam1/refreshrator/util/S3Uploader.java
Labels: feature

#67 Feature/#66 이미지 삭제 API
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/entity/Image.java
  src/main/java/com/hackathonteam1/refreshrator/entity/Recipe.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: feature

#70 Feature/#59 레시피 추천 API
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/entity/FridgeItem.java
  src/main/java/com/hackathonteam1/refreshrator/repository/RecipeRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: feature

#79 Feature/#76 레시피, 이미지 관련 리팩토링
  src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/ModifyRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/RegisterRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/file/ImageDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/DetailRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/RecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/RecipeListReponseDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/RecipeResponseDto.java
  src/main/java/com/hackathonteam1/refreshrator/entity/Recipe.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/repository/RecipeLikeRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: refactor

#81 Feature/ cors 설정 추가
  src/main/java/com/hackathonteam1/refreshrator/authentication/AuthenticationInterceptor.java
  src/main/java/com/hackathonteam1/refreshrator/config/CorsConfig.java
Labels: feature

#56 Feature/#48 배포 작업
  Dockerfile
  src/test/java/com/hackathonteam1/refreshrator/RefreshratorApplicationTests.java
Labels: feature

#83 Feature/#82 HealthController 작성
  src/main/java/com/hackathonteam1/refreshrator/controller/HealthController.java
Labels: enhancement

#85 Feature/#84 페이지네이션 사용 시 누락된 예외처리 작성
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: enhancement, refactor

#87 Feature/#86 CI/CD 적용
  .github/workflows/gradle.yml
Labels: feature

#89 Feature/#88 자신이 작성한 레시피 조회 API
  src/main/java/com/hackathonteam1/refreshrator/config/AuthenticationConfig.java
  src/main/java/com/hackathonteam1/refreshrator/controller/UserController.java
  src/main/java/com/hackathonteam1/refreshrator/repository/RecipeRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: feature

#91 Feature/#90 RecipeDto 내용 추가, 인증 경로 수정
  src/main/java/com/hackathonteam1/refreshrator/authentication/AuthenticationInterceptor.java
  src/main/java/com/hackathonteam1/refreshrator/config/AuthenticationConfig.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/DetailRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/RecipeDto.java
Labels: enhancement

#95 Feature/#92 refreshtoken 추가.
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/hackathonteam1/refreshrator/config/AuthenticationConfig.java
  src/main/java/com/hackathonteam1/refreshrator/config/RedisConfig.java
  src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/auth/TokenResponseDto.java
  src/main/java/com/hackathonteam1/refreshrator/entity/RefreshToken.java
  src/main/java/com/hackathonteam1/refreshrator/exception/RedisException.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
  src/main/java/com/hackathonteam1/refreshrator/util/RedisUtil.java
Labels: feature
