Repository mju-likelion/12th-hackathon-team1-server, pull requests merged in 2024-09, with the labels that each got.

#123 Feature/#118 인증 경로 수정, UriMatcher 유틸 클래스 작성, 인터셉터 리팩토링
  src/main/java/com/hackathonteam1/refreshrator/authentication/AuthenticationInterceptor.java
  src/main/java/com/hackathonteam1/refreshrator/config/AuthenticationConfig.java
  src/main/java/com/hackathonteam1/refreshrator/util/UriMatcher.java
Labels: enhancement, refactor

#125 Feature/#124 이미지 서비스 리팩토링
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/ModifyRecipeDto.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
  src/main/java/com/hackathonteam1/refreshrator/service/ImageService.java
  src/main/java/com/hackathonteam1/refreshrator/service/ImageServiceImpl.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: refactor

#122 Refactor/#121 재료 저장, 수정 코드 리펙토링
  src/main/java/com/hackathonteam1/refreshrator/entity/FridgeItem.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/IngredientService.java
Labels: refactor

#120 Refactor/#117 회원가입 중복확인 리펙토링
  src/main/java/com/hackathonteam1/refreshrator/entity/User.java
  src/main/java/com/hackathonteam1/refreshrator/repository/UserRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
Labels: refactor

#119 Refactor/#116 fridgeService 및 IngredientService 리팩토링과 코드 단순화
  .gitignore
  src/main/java/com/hackathonteam1/refreshrator/config/CorsConfig.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/fridge/FridgeItemDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/ingredient/IngredientDto.java
  src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/IngredientService.java
Labels: refactor

#128 Refactor/#127 checkEmailDuplicated
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
Labels: bug

#131 Feature/#126 토큰 관련 리팩토링
  src/main/java/com/hackathonteam1/refreshrator/authentication/AuthenticationExtractor.java
  src/main/java/com/hackathonteam1/refreshrator/authentication/AuthenticationInterceptor.java
  src/main/java/com/hackathonteam1/refreshrator/authentication/JwtTokenProvider.java
  src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/auth/CookiesResponse.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/auth/TokenResponseDto.java
  src/main/java/com/hackathonteam1/refreshrator/entity/RefreshToken.java
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
  src/main/java/com/hackathonteam1/refreshrator/service/TokenService.java
  src/main/java/com/hackathonteam1/refreshrator/util/AccessTokenUtil.java
  src/main/java/com/hackathonteam1/refreshrator/util/RedisUtil.java
  src/main/java/com/hackathonteam1/refreshrator/util/RefreshTokenUtil.java
Labels: refactor

#132 Refactor/#130 checkUser분리
  src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/UserService.java
Labels: refactor

#136 Feature/#135 레시피의 좋아요 관련 기능 및 validation 리팩토링
  src/main/java/com/hackathonteam1/refreshrator/authentication/AuthenticationInterceptor.java
  src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java
  src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java
  src/main/java/com/hackathonteam1/refreshrator/controller/UserController.java
  src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/RecipeIdListDto.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipeLike/RecipeLikedData.java
  src/main/java/com/hackathonteam1/refreshrator/dto/response/recipeLike/RecipeLikedDataList.java
  src/main/java/com/hackathonteam1/refreshrator/repository/RecipeLikeRepository.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
  src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
  src/main/java/com/hackathonteam1/refreshrator/service/UserService.java
Labels: refactor

#134 Refactor/#129 로그인 할때 이메일,비밀번호 검사 분리
  src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
  src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/UserService.java
Labels: refactor

#138 Refactor/#137 inject userservice
  src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java
  src/main/java/com/hackathonteam1/refreshrator/controller/UserController.java
  src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
  src/main/java/com/hackathonteam1/refreshrator/service/ImageServiceImpl.java
  src/main/java/com/hackathonteam1/refreshrator/service/IngredientService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
  src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
Labels: bug
